# Generated by Django 5.1.6 on 2025-03-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiDataCristian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=255)),
                ('rol', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
