# Generated by Django 5.1.6 on 2025-03-03 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_apidatacristian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apidatacristian',
            old_name='nombre_perfil',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='apidatacristian',
            old_name='rol',
            new_name='ubicacion',
        ),
        migrations.AddField(
            model_name='apidatacristian',
            name='stock',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
